# Generated by Django 4.0.3 on 2022-04-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customer_fullname', models.CharField(max_length=100, null=True)),
                ('customer_email', models.CharField(max_length=100, null=True)),
                ('customer_pass', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
